### ISSUE TITLE
[1.1] Milestone 1 & Understanding initial requirements

### ISSUE THREAD

**Issue by SIT-EddieTan** [INF2001-Team10-6/Software-Project#29]
Our client, a music school, has requested the development of a content management system (CMS) to streamline scheduling, content creation, and student registration processes. The initial requirements for this project include:

- [ ] The CMS should be web-based and implemented in a programming language of your choice.

- [ ] The system should provide the school manager with an immediate visualization of staff workloads upon landing on the homepage.

- [ ] The manager should have the ability to assign tasks to staff members on a weekly basis.

- [ ] The manager should be able to access the availability of up to three staff members, along with any relevant information that would facilitate job allocation.

- [ ] When displaying staff availability, the system should present information such as workload, staff job preferences, location, and weekly availabilities for effective job assignment.

- [ ] The manager's landing page should highlight the top three staff members with the lowest workloads and identify all staff members with over 40 hours of allocated work.

- [ ] Staff members should be able to view their weekly job assignments and assess their overall monthly workload from their personal landing pages.

- [ ] Staff members have the capability to add and modify their availabilities up to five weeks in advance.

- [ ] Staff members can express their job preferences for the upcoming week.

- [ ] Staff members can reject job assignments, but the system will prompt them to discuss the rejections with their manager before finalizing.

- [ ] System administrators responsible for IT operations within the company will oversee the addition of new staff members and managers to the CMS.
